score-spec/score-k8s

internal/annotations.go, internal/convert/workloads.go, internal/convert/workloads_test.go, internal/project/state.go, internal/provisioners/default/zz-default.provisioners.yaml, main_generate.go, main_generate_test.go, main_init.go, main_init_test.go
While working with dapr I found the following issues: 
1. The match expressions could be simplified to match labels - and making it compatible with Dapr.
=> fix: improved service match labels

internal/convert/container_resources.go, internal/convert/container_resources_test.go
Hit a panic when converting a resources section that had resource requests but no limits.
This PR fixes it and adds a regression test.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1031c3870]
goroutine 1 [running]:
github.com/score-spec/score-k8s/internal/convert.buildResourceList(0x0)
/home/runner/work/score-k8s/score-k8s/internal/convert/container_resources.go:45 +0x30
github.com/score-spec/score-k8s/internal/convert.convertContainerResources(0x14000498420)
/home/runner/work/score-k8s/score-k8s/internal/convert/container_resources.go:33 +0x5c
github.com/score-spec/score-k8s/internal/convert.ConvertWorkload(0x1400049dc00, {0x1400061e2b0, 0xd}) …
```
=> fix(convert): fixed panic in resource limits conversion

README.md, internal/provisioners/default/zz-default.provisioners.yaml
This copies the existing postgres provisioner and adapts it for mysql.
This was tested with a score file that looks like:
```
apiVersion: score.dev/v1b1
metadata:
name: demo-app
containers:
main:
image: ghcr.io/astromechza/demo-app:v0.6.1
variables:
OVERRIDE_MYSQL: ${resources.db.username}:${resources.db.password}@tcp(${resources.db.host}:${resources.db.port})/${resources.db.name}
service:
ports:
web:
port: 8080
resources:
db:
type: mysql
```
Which correctly verified that the database DSN for mysql was valid and connected ok.
Unlike score-compose, this provisioner uses a single database per instance model - which is generally ok for the moment as a proof of concept and providing some basic support.
Fixes #13 .
=> feat(provisioners): added default mysql provisioner

.github/workflows/release.yaml, .goreleaser.yaml
Same change as we made to score-compose and similar projects, the goreleaser version needs upgrading and fixed to a specific v2 of the internal binary.
⚒️
=> fix(ci): fix goreleaser args

internal/convert/workloads.go, internal/convert/workloads_test.go
This was mentioned in #25 as causing issues with deployments that have an HPA or have been scaled up by hand already. I'm not entirely sure why we had this default, possibly due to a previous proof of concept or example. Not breaking change since 1 is the default replicas. 
Thanks @maxstepanov for bringing this to our attention!
=> fix: remove default replicas=1 value from workload conversion

internal/provisioners/default/zz-default.provisioners.yaml
This PR adds the **RabbitMQ(amqp)** provisioner to the default provisioners of score-k8s . Fixes #11 
This was tested with a score file that looks like:
```yaml
apiVersion: score.dev/v1b1
metadata:
name: pika-python-client
containers:
pika_client:
image: python
variables:
amqp_connection_string : ${resources.amqp1.connection}
resources:
amqp1:
type: amqp
```
=> added amqp(rabbitmq) default provisioner to score-k8s

main_generate.go, main_generate_test.go
Similar to https://github.com/score-spec/score-compose/issues/173 but for the k8s provided.
=> fix: reject --image when multiple score files are provided

internal/annotations.go, internal/convert/workloads.go, internal/convert/workloads_test.go, internal/provisioners/core.go
- Default `Service` name now as the `Workload`, removing the `-svc` suffix
- New annotation to override it: `k8s.score.dev/service-name`
=> Default `Service` name now as the `Workload`, removing the `-svc` suffix + new annotation to override it `k8s.score.dev/service-name`

internal/provisioners/core.go
Hello, this PR closes issue #31 by changing the error message from 
`Error: failed to provision resources: The resource 'environment.default#my-sample-workload.env' is not supported by any existing provisioner.`
to 
`Error: failed to provision resources: The resource 'environment.default#my-sample-workload.env' is not supported by any existing provisioner. Please implement a custom resource provisioner to support this resource type.`
=> Improve error messaging on unsupported resource types. Closes issue #31

README.md, internal/provisioners/loader/load.go, main_init.go, main_init_test.go
This is the same `--provisioners` flag from `score-compose` for loading in remote sources as score provisioners.
=> feat: added --provisioners flag from score-compose

internal/provisioners/default/zz-default.provisioners.yaml
More security for the default `postgres` provisioner:
- `postgres:17-alpine`
- `securityContext`
- `automountServiceAccountToken=false`
Tested with this app: https://github.com/score-spec/sample-score-app.
`k get pods`:
```
NAME                           READY   STATUS    RESTARTS        AGE
hello-world-6bf94c85dc-h54rl   1/1     Running   3 (9m38s ago)   9m55s
pg-hello-world-edea9043-0      1/1     Running   0               9m57s
```
`curl $(score-k8s resources get-outputs dns.default#hello-world.dns --format '{{ .host }}')`:
```
<html>
<body>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script …
```
=> `postgres:17-alpine` + `securityContext`

internal/provisioners/default/zz-default.provisioners.yaml
More security for the default `mongodb` provisioner:
- `securityContext`
- `automountServiceAccountToken=false`
Tested with this app: https://github.com/Humanitec-DemoOrg/aks-store-demo.
`k get pods`:
```
NAME                                   READY   STATUS    RESTARTS   AGE
makeline-service-8c8765477-vg9tz       1/1     Running   0          70s
mongo-makeline-service-333c150c-0      1/1     Running   0          71s
order-service-6b49d7ff76-f7j8v         1/1     Running   0          70s
product-service-79c8d47575-vh5px       1/1     Running   0          69s
rabbitmq-makeline-service-4be9c8f3-0   1/1     Running   0          71s
store-admin-559f9f546b-6bmxg           1/1     Running   0          69s
store-front-54bc46cb96-nkzjc           1/1     Running   0          68s
```
`k logs …
=> Update zz-default.provisioners.yaml - `securityContext` for `mongodb`

internal/provisioners/default/zz-default.provisioners.yaml
More security for the default `redis` provisioner:
- `securityContext`
- `automountServiceAccountToken=false`
Tested with this app: https://github.com/Humanitec-DemoOrg/onlineboutique-demo.
=> Update zz-default.provisioners.yaml - `securityContext` for `redis`

.github/dependabot.yml, .github/workflows/release.yaml
Create `dependabot.yml` to automate the process of upgrading go, Docker and GHA actions versions. This will avoid these manual actions needed in the past:
- https://github.com/score-spec/score-k8s/pull/41
Also took the opportunity to avoid the double run of the CI in a PR, so now CI (`release`) is triggered either on PR or in a push on `main`.
=> Create dependabot.yml and fix CI for push on main OR pull_request

.dockerignore, .github/dependabot.yml, .github/workflows/ci.yaml, .github/workflows/release.yaml, Dockerfile
The main purpose of this PR is to fix #40 
Added the Dockerfile , and release.yml for making the score-k8s image
This PR main purpose is to make the docker image for the score-k8s like the rest 
- [] Breaking change (fix or feature that would cause existing functionality to change)
=> Added the Dockerfile for the score-k8s and release too

.github/workflows/ci.yaml, main_init.go
Fix bug where score-k8s creates the score.yaml with perm 0600 instead of 0755.
Fix bug where score-k8s creates the score.yaml with perm 0600 instead of 0755. This is to keep it consistent with other commands like scope-compose which creates it with 0755 perm. Also the ci workflow has been changed to cat the file rather than listing it.
- Create score.yaml file with 0755 permissions
- Make the "Test Docker Image" CI to cat the file rather than listing it.
=> #57 Fix bug where score-k8s creates the score.yaml with perm 0600 instead of 0755

.goreleaser.yaml
snapshot.name_template was deprecated  so it was updated by a new version_template
=> updated the goreleaser by removing deprecation

main_init.go
Added the OCI example as said in [here](https://github.com/score-spec/score-compose/issues/178)
This pr added a new example and also fixed a typo.
=> Added oci example in `score-k8s init --help`

README.md, internal/provisioners/default/zz-default.provisioners.yaml
=> Small updates for consistency

README.md, internal/provisioners/default/zz-default.provisioners.yaml
Adding a new default provider for a mssql database.
Created a new default provider template for a mssql db based on already existing mysql and postgres ones. Updated zz-default.provisioners.yaml and README.md.
Adding a new default provider for a mssql database per feature request https://github.com/score-spec/score-k8s/issues/66
Was tested with the following score.yaml file:
```
apiVersion: score.dev/v1b1
metadata:
name: test-container
containers:
main:
image: mcr.microsoft.com/mssql-tools
variables:
SERVER_NAME: ${resources.db.host}
MSSQL_SA_USER: ${resources.db.username}
MSSQL_SA_PASSWORD: ${resources.db.password}
command:
- /bin/sh
- -c
- /opt/mssql-tools/bin/sqlcmd -S $SERVER_NAME -U $MSSQL_SA_USER -P $MSSQL_SA_PASSWORD -Q "select @@version"
resources:
db:
type: mssql
```
Once …
=> feature(provisioner) Add a default mssql provisioner

internal/command/check_version.go, internal/command/check_version_test.go, internal/version/version.go, internal/version/version_test.go
**This PR main purpose is to add the subcommand `check-version` with test cases...**
=> Adding check-version subcommand

internal/provisioners/default/zz-default.provisioners.yaml
Like for `score-compose`, let's use `mysql:8` instead of `mysql:8.0` allowing to use `8.4.3` currently, latest LTS instead of `8.0.40`.
https://github.com/score-spec/score-compose/blob/main/internal/command/default.provisioners.yaml#L582
=> Update zz-default.provisioners.yaml - `mysql:8`

Dockerfile
Like done there: https://github.com/score-spec/score-compose/pull/203.
=> `gcr.io/distroless/static` instead of `scratch`

.github/workflows/ci.yaml
Get a confirmation signal on main branch merge.
=> chore: enable ci on main push

README.md, internal/convert/container_files.go, internal/provisioners/default/zz-default.provisioners.yaml
Fixes: #65 
This PR brings some much needed compatibility with `score-compose` by adding an s3 bucket provisioner by default using an in-cluster object storage based on minio.
This follows the current best practises of k8s provisioner development:
1. A single minio instance is created with stateful set and PVC based data storage. The pods run as non-root.
2. A k8s Service is created routing both api and console ports to the minio instance.
3. An s3 bucket is created per `s3` resource. We intentionally use a shared access key across all buckets for now to match score-compose behavior.
4. All secret outputs are encoded as references to in-cluster secrets.
**testing**
This was tested with the following score file:
```
apiVersion: score.dev/v1b1
metadata:
name: demo-app
containers:
main: …
```
=> Adding an s3 default provisioner based on minio

go.mod, go.sum
`go get -u golang.org/x/net` to fix https://github.com/score-spec/score-k8s/security/dependabot/4
=> golang.org/x/net bump

Dockerfile
Update Dockerfile - pinned digest for base container images:
- https://github.com/score-spec/score-k8s/security/code-scanning/14
- https://github.com/score-spec/score-k8s/security/code-scanning/13
=> Update Dockerfile - pinned digest for base container images

go.mod
chore: update go to 1.23.5
For some reasons, Dependabot is not picking this up...
https://github.com/score-spec/score-k8s/blob/main/.github/dependabot.yml#L11
=> chore: update go to 1.23.5

internal/provisioners/default/zz-default.provisioners.yaml
Update zz-default.provisioners.yaml - remove unused name for mongodb, it's not used, let's avoid any confusion.
=> Update zz-default.provisioners.yaml - remove unused name for mongodb

README.md, internal/provisioners/default/zz-default.provisioners.yaml, internal/secrets.go, internal/secrets_test.go
In conversation with @mathieu-benoit, we found that secret references were difficult to work with in bash-based command provisioners because of the lack of base64url encoding tools in many distros. Examining the secret and key spec in k8s shows that there is actually a limited set of possible characters none of which are particularly bad to encode — so we can actually drop the base64 encoding entirely. Note that we have to switch the separator character to `_` which can't be confused with valid characters in a secret name.
With this change, a bash based provisioner can now work with just:
```
- uri: cmd://bash#example-provisioner
type: example-provisioner-resource
class: default
id: specific
args: ["-c", "echo '{\"resource_outputs\":{\"key\":\"value\",\"secret\":\"🔐💬mysecret_mykey💬🔐\"},\"m …
```
=> feat: new and easier secret reference schema

README.md, go.mod, go.sum, internal/command/generate.go, internal/command/generate_test.go, internal/command/init.go, internal/command/init_test.go, internal/patching/patching.go, internal/project/state.go
And based on the success of https://github.com/score-spec/score-compose/pull/276 in score-compose, I'm pleased to present the addition of the `--patch-templates` feature for `score-k8s`!
This can be used to:
* inject additional manifests
* modify properties on existing ones
* replace manifests with different kinds or CRDs
This addresses #25 and #35. As well as Slack requests like https://cloud-native.slack.com/archives/C07DXMABPC4/p1741769300965929
Tested through unit tests today. 
I've noted the deprecation of the previous, kind of useless, `--patch-manifests` CLI option which can be removed in the future.
=> feat: added --patch-templates and deprecated --patch-manifests

internal/provisioners/default/zz-default.provisioners.yaml
Smaller image by default for the `amqp` provisioner like we already have in `score-compose`: https://github.com/score-spec/score-compose/blob/main/internal/command/default.provisioners.yaml#L367.
Before: `261MB`, after: `178MB` --> `83MB` saved uncompressed on disk.
=> Update zz-default.provisioners.yaml - rabbitmq:alpine

internal/patching/patching.go
cc @mathieu-benoit 
When we debug issues related to patching output, we need to indicate to users that they should run with `-vv` to debug this unmarshalling error. Since Go unmarshal errors are often quite opaque. We don't have a more useful schema to run this against.
=> chore: added debug message to debug failed patch output

internal/provisioners/default/zz-default.provisioners.yaml
Use `mirror.gcr.io/` to avoid DockerHub rate limits error while using default provisioners:
- https://docs.docker.com/docker-hub/usage/
- https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images
- https://devtron.ai/blog/dodging-docker-hub-rate-limits-the-ultimate-cheat-code-for-your-ci-cd-pipeline/
> Starting April 1, 2025, all users with a Pro, Team, or Business subscription will have unlimited Docker Hub pulls with fair use. Unauthenticated users and users with a free Personal account have the following pull limits:
> - Unauthenticated users: 10 pulls/hour
> - Authenticated users with a free account: 100 pulls/hour
=> Use `mirror.gcr.io/` to avoid DockerHub rate limits error while using default provisioners

internal/provisioners/default/zz-default.provisioners.yaml
Update zz-default.provisioners.yaml - `service-port` fail if not found
=> Update zz-default.provisioners.yaml - `service-port` fail if not found
